#!/usr/bin/env bash

# ----------------------------------------------------------------------------
#  SecureChat hvigor startup script (forwarder), version 1.0.0
#
#  Forwards to the hvigorw bundled with DevEco Studio.
#
#  Required ENV vars:
#  ------------------
#    NODE_HOME - location of a Node home dir
#    or
#    Add /usr/local/nodejs/bin to the PATH environment variable
# ----------------------------------------------------------------------------

set -e

HVIGOR_APP_HOME="$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")"

# Location of the DevEco-bundled hvigor wrapper. Override with DEVECO_HVIGOR_HOME.
if [ -z "${DEVECO_HVIGOR_HOME}" ]; then
  DEVECO_HVIGOR_HOME="/e/Program Files/Huawei/DevEco Studio/tools/hvigor"
fi
HVIGOR_WRAPPER_SCRIPT="${DEVECO_HVIGOR_HOME}/bin/hvigorw.js"

#NODE_OPTS="--max-old-space-size=8192  --expose-gc"

warn() {
	echo ""
	echo -e "\033[1;33m`date '+[%Y-%m-%d %H:%M:%S]'`$@\033[0m"
}

error() {
	echo ""
	echo -e "\033[1;31m`date '+[%Y-%m-%d %H:%M:%S]'`$@\033[0m"
}

fail() {
	error "$@"
	exit 1
}

# Determine node to start hvigor wrapper script
if [ -n "${NODE_HOME}" ];then
   # unix path
   if [ -x "${NODE_HOME}/bin/node" ];then
      EXECUTABLE_NODE="${NODE_HOME}/bin/node"
   # windows path
   elif [ -x "${NODE_HOME}/node.exe" ];then
      EXECUTABLE_NODE="${NODE_HOME}/node.exe"
   else
      fail "ERROR: NODE_HOME is set to an invalid directory,check $NODE_HOME\n\nPlease set NODE_HOME in your environment to the location where your nodejs installed"
   fi
else
   EXECUTABLE_NODE="node"
   which ${EXECUTABLE_NODE} > /dev/null 2>&1 || fail "ERROR: NODE_HOME is not set and not 'node' command found in your path"
fi

# Check hvigor wrapper script
if [ ! -r "$HVIGOR_WRAPPER_SCRIPT" ];then
	fail "ERROR: Couldn't find hvigorw.js in ${DEVECO_HVIGOR_HOME}/bin\n\nPlease set DEVECO_HVIGOR_HOME to your DevEco Studio hvigor directory"
fi

if [ -z "${NODE_OPTS}" ]; then
  NODE_OPTS="--"
fi

# start hvigor-wrapper script
exec "${EXECUTABLE_NODE}" "${NODE_OPTS}" \
	"${HVIGOR_WRAPPER_SCRIPT}" "$@"
